# Generated by Django 4.0.6 on 2022-07-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
