# Generated by Django 4.0.6 on 2022-07-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('amount_paid', models.CharField(max_length=100)),
                ('volume_dispensed', models.IntegerField(max_length=50)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
