# Generated by Django 4.0.6 on 2022-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='volume_dispensed',
            field=models.IntegerField(),
        ),
    ]
