# Generated by Django 4.0.6 on 2022-07-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycs', '0002_alter_kyc_volume_dispensed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='created_by',
        ),
    ]
