# Generated by Django 4.0.6 on 2022-07-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycs', '0004_kyc_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='role',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
