# Generated by Django 4.0.6 on 2022-07-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycs', '0005_kyc_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='role',
        ),
    ]
